package.json, packages/client/src/index.js
=> force publish

.github/workflows/test-libs.yml, package.json
Added exact to versionup
* added jest pipeline
* added exact key to lerna version
---
=> chore: ✨ added exact to package.json

.github/workflows/test-libs.yml, package.json
=> Publish CI

.husky/commit-msg, commitlint.config.js, lerna.json, package.json, yarn.lock
=> Publish commit changes

.github/workflows/release.yml
=> publish changes

packages/client-core/lib/FireboltFormEngine.ts, packages/client-core/lib/services/API.ts, packages/client/src/components/FireboltProvider/hook/index.ts, packages/lab/src/app/components/templates/UploadFileTemplate.jsx, packages/lab/src/app/pages/debug/FormDemo.jsx
* Adjustments on upload file function
* Task: https://redventures.atlassian.net/jira/software/c/projects/IQL/boards/1582?modal=detail&selectedIssue=IQL-7572
=> feat: ✨ upload files to aws s3

packages/blueberry/Widgets/CheckboxGroupWidget/index.jsx, packages/lab/src/app/components/templates/DefaultTemplate.jsx, packages/lab/src/app/pages/debug/FormDemo.jsx
* Fixed the checkboxgroup widget to support the columns prop
=> fix: 🐛 checkboxgroup widget missing columns prop

.github/workflows/test-libs.yml
=> ci(all): :construction_worker: changed node version on test ci

packages/validators/src/validators/numberRange/index.ts, packages/validators/src/validators/numberRange/numberRange.test.ts
=> Fix/iql 7691/fix validator decimal

packages/client-core/lib/FireboltFormEngine.ts, packages/client-core/lib/types.ts, packages/client/src/components/FireboltProvider/hook/index.ts, packages/client/src/helpers/createFireboltProvider.tsx, packages/client/src/types.ts, packages/lab/src/app/components/templates/DefaultTemplate.jsx, packages/lab/src/app/pages/debug/FormDemo.jsx
Fixed the firebolt debug mode, that enables us to debug form steps locally. this features stopped working correctly after the addition of the addons feature (https://github.com/IQ-tech/firebolt/pull/49). 
---
---
=> fix(client-core): :bug: fixed step debugger used on firebolt lab

.github/workflows/test-libs.yml, CONTRIBUTING.md, packages/blueberry/Widgets/CheckboxGroupWidget/index.jsx, packages/client-core/lib/FireboltFormEngine.ts, packages/client-core/lib/services/API.ts, packages/client-core/lib/types.ts, packages/client/src/components/FireboltProvider/hook/index.ts, packages/client/src/helpers/createFireboltProvider.tsx, packages/client/src/types.ts, packages/lab/src/app/components/templates/DefaultTemplate.jsx, packages/lab/src/app/components/templates/UploadFileTemplate.jsx, packages/lab/src/app/pages/debug/FormDemo.jsx, packages/validators/src/validators/numberRange/index.ts, packages/validators/src/validators/numberRange/numberRange.test.ts
New Firebolt version release
* Added contributing
* Fixed number range validator (issues with decimal point)
* Fixed upload file handler (client-core)
* Fixed debug step on client and client-core
=> fbt release

packages/client/src/components/FireboltForm/hook/useFormState.ts
Form errors were being cleared after onBlur event
https://user-images.githubusercontent.com/17283501/166984921-ca8d555a-702e-485d-a2ea-5a63fb62382e.mov
---
---
=> fix(client): :bug: fixed form cleaning error on onblur

packages/br-addons/src/constants/nationalities.js, packages/br-addons/src/props-presets.js
Add nationality preset to BR addon, according to what has been asked fo BV form. 
(fixed previous PR where a lot of development commits where here by mistake 😅 )
=> feat(client): :sparkles: add nationality preset to br-addon

packages/validators/src/validators/legalAge/legalAge.test.ts
* real world current date broke date test
---
---
=> test(validators): fixed date test

packages/engine/src/types.ts, packages/json-schema/form-schema.json
* Updated the JSON Schema to support Firebolt Engine
=> Feat/iql 7526/update json schema

packages/client/src/components/FireboltForm/hook/index.ts, packages/client/src/components/FireboltForm/hook/useFormEvents.ts, packages/client/src/components/FireboltForm/index.tsx, packages/client/src/components/FireboltProvider/hook/index.ts, packages/client/src/components/FireboltProvider/hook/useData.ts, packages/client/src/components/StepForm/index.tsx, packages/client/src/components/Wizard/Step/hook.ts, packages/client/src/context.ts, packages/client/src/types.ts, packages/lab/src/app/pages/debug/FormDemo.jsx
Remote errors were not being cleaned
---
---
=> fix(client): :bug: fixed bug with remote errors

packages/validators/src/validators/name/index.ts, packages/validators/src/validators/name/name.test.ts
Fix validators
- Have any word at least 2 chars, skips char e
- Have any blacklisted word
Add validators
- Dont have any word with starts or ends with a single char
- Have any word greater than max word length
=> fix: some name validators

packages/client/src/components/FireboltForm/hook/useFormEvents.ts, packages/lab/src/app/components/templates/DefaultTemplate.jsx, packages/lab/src/app/pages/debug/FormDemo.jsx
* removed console.log
* fixed lab url
---
---
=> fix(client): :bug: removed console.log

packages/client/src/components/FireboltForm/hook/index.ts, packages/client/src/components/FireboltForm/hook/useFormEvents.ts, packages/client/src/components/FireboltForm/hook/useFormState.ts, packages/client/src/components/FireboltForm/index.tsx, packages/client/src/components/FireboltProvider/hook/index.ts, packages/client/src/components/FireboltProvider/hook/useData.ts, packages/client/src/components/StepForm/index.tsx, packages/client/src/components/Wizard/Step/hook.ts, packages/client/src/context.ts, packages/client/src/types.ts, packages/lab/src/app/components/templates/DefaultTemplate.jsx, packages/lab/src/app/pages/debug/FormDemo.jsx, packages/validators/src/validators/name/index.ts, packages/validators/src/validators/name/name.test.ts
release latest version
---
---
=> Release new latest

packages/validators/src/validators/email/email.test.ts, packages/validators/src/validators/email/index.ts
This PR add accent validation on email
=> fix(validators): 🩹 add accents validator on email

packages/blueberry/Widgets/TextWidget/index.jsx
=> feat(blueberry-theme): added maxLength

packages/br-addons/src/props-presets.js
=> feat: :sparkles: added new generic account number preset

packages/br-addons/src/props-presets.js
adding two news generic account preset
=> feat: :sparkles: adding two news generic account preset

packages/validators/src/validators/name/index.ts, packages/validators/src/validators/name/name.test.ts
* added backslash check to name validator
---
---
=> small fixes

packages/validators/src/validators/email/email.test.ts, packages/validators/src/validators/email/index.ts
=> fix(validators): :bug: fixed validators label

packages/client/src/components/FireboltForm/index.tsx
=> added data attr to fireboltform

packages/client/src/components/FireboltProvider/hook/index.ts, packages/client/src/components/FireboltProvider/hook/useStates.ts, packages/client/src/components/Wizard/hook.ts, packages/client/src/context.ts, packages/client/src/types.ts, packages/lab/src/app/pages/debug/FormDemo.jsx
added formPayload to onBeforeProceed callback on wizard
---
---
=> feat(client): added payload to new hook

packages/client/src/components/FireboltForm/hook/useFormEvents.ts
=> [IQL-8628] - Removing repeated spaces from the payload field

packages/validators/src/validators/nonRepeatedChars/index.ts, packages/validators/src/validators/nonRepeatedChars/nonRepeatedChars.test.ts
=> [IQ-tech] - Adding a parameter to ignore spaces 

packages/client/src/components/FireboltProvider/hook/index.ts
This pr handle with unexpected error on firebolt-api call.
=> Unexpected error handler on api response

packages/validators/src/functions/validateFBTField/index.ts, packages/validators/src/functions/validateFBTStep/index.ts, packages/validators/src/index.ts, packages/validators/src/types.ts, packages/validators/src/utils/replaceAll.ts, packages/validators/src/validators/numberRange/index.ts
* removed native replaceAll due to compatibility issues
---
---
=> feat(validators): :sparkles: added internal replaceAll

packages/client/src/components/FireboltForm/InputHolder/hook/index.ts, packages/client/src/components/FireboltForm/InputHolder/hook/useMask.ts, packages/lab/src/app/components/templates/DefaultTemplate.jsx
Backend sent field errors UI fixed
When multiple field errors came from the back end, the red border on UI was bugging to disappear.
This was fixed.
---
The errors weren't showing correctly, and needed to be fixed.
---
---
=> fix(client): :bug: backend sent field errors UI fixed

packages/client/src/components/FireboltForm/hook/useFormState.ts
=> Iql 9543/fix/input fields errors

packages/client/src/components/FireboltForm/InputHolder/hook/index.ts, packages/client/src/components/FireboltForm/hook/useFormState.ts, packages/lab/src/app/components/templates/DefaultTemplate.jsx
=> fix(client): removed unused filter on clear field error

packages/blueberry/Widgets/CheckWidget/index.jsx, packages/lab/src/app/components/templates/DefaultTemplate.jsx
=> fix: fixed checkbox onBlur evt

packages/client/src/components/FireboltForm/InputHolder/hook/index.ts, packages/client/src/components/FireboltForm/hook/helpers/remapFormChildren.ts, packages/client/src/components/FireboltForm/hook/useFormRendering.tsx
* fixed inserts apply order
---
---
=> fix: inserts are being applied correctly

packages/client/src/components/FireboltProvider/hook/index.ts
Fixed a bug to change the track on the last step.
Fixed a bug that made the form end if it tries to change the track on the last step
---
On BB ourocard we need to change the form track after the last step. This wasn't working, and the form was just ending.
---
=> fix(client): :bug: fixed change track on last step

packages/client/src/components/FireboltForm/InputHolder/hook/index.ts
=> feat: added value valid to event handlers on fireboltform

packages/client/src/components/FireboltForm/InputHolder/hook/index.ts, packages/client/src/components/FireboltForm/hook/useFormState.ts, packages/lab/src/app/components/templates/DefaultTemplate.jsx
=> fix: :bug: fixed step form onChange prop callback payload

packages/validators/src/validators/noSpecialCharacters/index.ts, packages/validators/src/validators/noSpecialCharacters/noSpecialCharacters.test.ts
The character ' - ' needs to be forbidden on the hasSpecialCharacters validator.
The validator hasSpecialCharacters didn't had the ' - ' as a forbidden character.
Since we were having problems with this character too, we need to put it on the list of forbidden characters.
=> feat: character ' - ' is forbidden on the validator hasSpecialCharacters

packages/validators/src/validators/phone/phone.test.ts
adding new number phone to test
---
=> feat(all): :sparkles: adding new number phone to test

packages/blueberry/index.js
The previous PR was missing this step of adding the widget to Firebolt theme
=> [IQL-10095] UploadWidget -  add widget to theme

.github/workflows/prerelease.yml, packages/atlas-theme/package.json
=> fix: 💚 node version

packages/atlas-theme/Widgets/BRCityWidget/hook.js, packages/atlas-theme/Widgets/BRCityWidget/index.jsx, packages/atlas-theme/helpers/getTooltipConfig.js, packages/atlas-theme/index.js, packages/atlas-theme/services/getCities.js
Add BRCityWidget to firebolt atlas theme
=> feat: add BRCityWidget

packages/atlas-theme/services/getAdress.js
=> test: replace stateformat to default

packages/atlas-theme/Widgets/TextWidget/index.jsx
=> test: trigger build

yarn.lock
=> chore: 💚 new build libds

packages/atlas-theme/Widgets/CheckWidget/index.jsx, packages/atlas-theme/index.js
This PR adds CheckBox Widget for Atlas Theme
=> feat: add checkbox widget for atlas

packages/atlas-theme/Widgets/CheckWidget/index.jsx
=> fix: add missing import

packages/atlas-theme/Widgets/NumberWidget/index.jsx, packages/atlas-theme/Widgets/TextWidget/index.jsx
This PR adds min and max properties to the aurora theme number input.
=> feat: adding min and max props on number input (aurora)

package-lock.json, packages/atlas-theme/Widgets/SelectWidget/index.jsx, yarn.lock
This PR adds a function to close Select Options when the user:
- clicks outside the widget
- or presses the ESC key
=> feat: add condition to close select when user clicks outside

packages/atlas-theme/Widgets/SelectSearchWidget/index.jsx
Fix close behavior on selectSearch atlas theme
---
---
---
=> fix: selectSearch close behavior

packages/atlas-theme/Widgets/SelectSearchWidget/index.jsx, packages/atlas-theme/Widgets/SelectWidget/index.jsx, packages/lab/src/app/pages/debug/FormDemo.jsx
This PR fix the empty label in onChange for SelectWidget and SelectSearchWidget
=> [ATLAS_THEME] FIX: Empty select labels

packages/atlas-theme/Widgets/SelectWidget/index.jsx
Remove observable to run effect only on component mount
=> [ATLAS-THEME] Fix: effect observable

packages/atlas-theme/Widgets/SelectSearchWidget/index.jsx, packages/atlas-theme/Widgets/SelectSearchWidget/styles.scss, packages/atlas-theme/Widgets/SelectWidget/index.jsx, packages/atlas-theme/Widgets/SelectWidget/styles.scss, packages/lab/src/app/pages/debug/FormDemo.jsx
- fix open behavior on SelectSearch
- fix display props on Select and SelectSearch widgets
- feat: add placeholder class to select fields
- feat: add empty state to SelectSearch
=> [ATLAS] FIX Select and SelectSearch components

packages/atlas-theme/Widgets/SelectSearchWidget/index.jsx
Revert last version.
Now its working greate on FormDemo
=> fix: revert version 83

packages/atlas-theme/Widgets/TextWidget/index.jsx
=> chore: trigger pipe

packages/aurora-theme/Widgets/NumberWidget/index.jsx
* Added  `maxLength` prop to the `NumberWidget` component (Aurora).
=> fix(aurora): add maxLength support to NumberWidget

packages/aurora-theme/Widgets/SelectWidget/index.jsx, packages/aurora-theme/package.json, yarn.lock
=> chore: update aurora

packages/aurora-theme/package.json, yarn.lock
=> chore: update aurora lib
